# fly.toml app configuration file generated for paas-vmess-trojan-argo-eeonfq on 2025-10-06T09:14:23Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'paas-vmess-trojan-argo-eeonfq'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 8
  memory_mb = 8192
